encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("search/", views.search, name="search"),
    path("wiki/<str:title>", views.render_wiki, name="renderwiki"),
    path("newpage", views.newpage, name="newpage"),
    path("edit/", views.edit, name="edit"),
    path("randompage/", views.randompage, name="randompage")
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/forms.py
from django import forms
from django.core.exceptions import ValidationError
from . import util

class NewPageForm(forms.Form):

    page_name = forms.CharField(label="", widget=forms.TextInput(attrs={"class": "search w-50 mb-3",
                                                                        'placeholder':'Enter a Page Name'}))
    content = forms.CharField(label="", widget=forms.Textarea(attrs={"class": "w-50 h-50", 
                                                                    "placeholder": "Enter the page content"}))
    def clean_page_name(self):
        name = self.cleaned_data['page_name']
        filenames = util.list_entries()

        for filename in filenames:
            if filename.lower() == name.lower():
                raise ValidationError("A page with this name already exists.")
            
        return name
    

encyclopedia/views.py
from django.shortcuts import render
import markdown
from django.http import HttpResponseRedirect
from django.urls import reverse
import random
from . import util
from .forms import NewPageForm



def converter(title):
    md_file = util.get_entry(title)
    markdown_trans = markdown.Markdown()
    if md_file == None:
        return None
    else:
        return markdown_trans.convert(md_file)

def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

def render_wiki(request, title):
    html_page = converter(title)
    if html_page == None:
        return render(request, "encyclopedia/render.html", {
            "Error": "No results"
        })
    else:
        return render(request, "encyclopedia/render.html", 
                    {"wiki": html_page,
                     "name": util.get_entry(title).split()[1]})

def search(request):
    if request.method == "POST":
        title = request.POST["q"]
        html_page = converter(title)

        if html_page is not None:
            return render(request, "encyclopedia/render.html", {
                "wiki": html_page, 
                "name": util.get_entry(title).split()[1]
            })
        else:
            is_substring = []
            entries = util.list_entries()

            for entry in entries:
                if title.lower() in entry.lower():
                    is_substring.append(entry)
            
            return render(request, "encyclopedia/search.html", {
                "entries": is_substring,
                "error": "No results"
            })

def newpage(request):
    if request.method == "POST":
        form = NewPageForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data["page_name"]
            content = form.cleaned_data["content"]
            util.save_entry(name, content)
            return HttpResponseRedirect(reverse('encyclopedia:renderwiki', args=[name]))
        else:
            return render(request, "encyclopedia/newpage.html", {
                "form": form,
            })

    else:
        return render(request, "encyclopedia/newpage.html", {
            "form": NewPageForm
        })
    
def edit(request):
    if request.method == "GET":
        name = request.GET["name"]
        content = util.get_entry(name)
        
        return render(request, "encyclopedia/edit.html", {
            "name": name,
            "content": content
        })
    else:
        name = request.POST["name"]
        content = request.POST["content"]
        util.save_entry(name, content)
        return HttpResponseRedirect(reverse('encyclopedia:renderwiki', args=[name]))

def randompage(request):
    pages = util.list_entries()
    return HttpResponseRedirect(reverse('encyclopedia:renderwiki', args=[random.choice(pages)]))

encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Edit
{% endblock %}

{% block body %}

    <h1>Edit</h1>

    <form action="{% url 'encyclopedia:edit' %}" method="post">
        {% csrf_token %}
        {{ name }} <br>
        <input type="hidden" name="name" value="{{ name }}">
        <textarea name="content" id="content_id" cols="30" rows="10" class="w-50 h-50">{{ content | safe }}</textarea> <br>
        <input type="submit" class="btn btn-primary">
    </form>
{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="{% url 'encyclopedia:renderwiki' title=entry %}" class="text-dark">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:search' %}" method="post">
                    {% csrf_token %}
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:newpage' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:randompage' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/newpage.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Search
{% endblock %}

{% block body %}

    <h1>Add New Page</h1>

    <form action="{% url 'encyclopedia:newpage' %}" method="post">

        {% csrf_token %}
        <label for="id_page_name" class="font-weight-bold">New Page Name:</label><br>
        {% if form.page_name.errors %}
            <div class="error">{{ form.page_name.errors.as_text }}</div>
        {% endif %}
        {{ form.page_name }} <br>
        

        <label for="id_content" class="font-weight-bold">New Page Content:</label><br>
        {{ form.content }} <br>

        <input type="submit" value="OK" class="btn btn-primary">
        
    </form>
{% endblock %}

encyclopedia/templates/encyclopedia/render.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ name }}
{% endblock %}

{% block body %}

    {% if wiki %}
        {{ wiki|safe }}

        <form action="{% url 'encyclopedia:edit' %}" method="get">
            {% csrf_token %}
            <input type="hidden" value="{{ name }}" name="name">
            <input type="hidden" value="{{ wiki }}" name="content">
            <input type="submit" value="Edit" class="btn btn-primary">
        </form>
        
    {% else %}
        <h2>{{ error }}</h2>
    {% endif %}
{% endblock %}

encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Search
{% endblock %}

{% block body %}

    <h1>Search</h1>

    <ul>
    {% for entry in entries %}
        <li><a href="/{{ entry }}">{{ entry }}</a></li>
    {% empty %}
        <li>{{ error }}</li>
    {% endfor %}
    </ul>
{% endblock %}